QQ: '*'
VIP_LAND:
    enable: true
    # 0: 不自动使用土地药水 1: 自动使用红土地药水
    use_and_tool: 1
    # 0: 不自动使用加速药水 1: 自动使用加速药水
    use_speed_tool: 1
    # 0: 不自动使用叶子药水 1: 自动使用掌状复叶药水
    use_leaf_tool: 1
    # 0: 不自动展示最高魅力值的花藤 1: 自动展示最高魅力值的花藤
    auto_show: 1
    # 0: 不自动出售花藤 1: 自动出售花藤
    auto_sale: 1
    # 出售时最少保留几个迷人藤
    save_amount: 0
